server:
  port: 7003
eureka:
  instance:
    hostname: eurekaServer7003 #eureka服务端的实例名称
  client:
    #不向注册中心注册自己
    register-with-eureka: false
    #自己就是注册中心，我的职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址(这里是集群配置，还需要在hosts文件中配置：访问地址+hostname)
      defaultZone: http://eurekaServer7001:7001/eureka,http://eurekaServer7002:7002/eureka